<!DOCTYPE html>
<html style="font-size: 16px;">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="utf-8">
  <meta name="keywords"
    content="Calon Kandidat KetuaHimpunan Mahasiswa Program StudiHukum Pidana Islam Fakultas Syariah">
  <meta name="description" content="">
  <meta name="page_type" content="np-template-header-footer-from-plugin">
  <title>hasil HPI</title>
  <link rel="stylesheet" href="nicepage.css" media="screen">
  <link rel="stylesheet" href="hasil.css" media="screen">
  <script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>
  <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
  <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
  <meta name="generator" content="Nicepage 3.7.1, nicepage.com">
  <link id="u-theme-google-font" rel="stylesheet"
    href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i">


  <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "",
		"url": "index.html"
}</script>
  <meta property="og:title" content="hasil">
  <meta property="og:type" content="website">
  <meta name="theme-color" content="#478ac9">
  <link rel="canonical" href="index.html">
  <meta property="og:url" content="index.html">
</head>

<body class="u-body u-overlap u-overlap-transparent">
  <header class="u-align-left u-clearfix u-header u-header" id="sec-ba2f">
    <div class="u-clearfix u-sheet u-sheet-1"></div>
  </header>
  <section class="u-clearfix u-hidden-sm u-section-1" id="sec-642a">
    <img src="images/Presentation1-removebg.png" alt="" class="u-expanded-width u-image u-image-default u-image-1"
      data-image-width="1277" data-image-height="193">
    <h2 class="u-align-center u-text u-text-1"><b style="">Sistem Pemilihan Umum<br>&nbsp;Fakultas Syariah<br>&nbsp;Hukum Pidana Islam</b>
      <br>
    </h2>
    <img src="images/Logo-iain.png" alt="" class="u-image u-image-default u-preserve-proportions u-image-2"
      data-image-width="400" data-image-height="432">
    <img src="images/logoKPUMFASYA.png" alt="" class="u-image u-image-default u-preserve-proportions u-image-3"
      data-image-width="970" data-image-height="1600"><br><br><br>
    <div id="chartContainer1" style="height: 400px; max-width: 1920px; margin: 0px auto;"></div>
  </section>


  <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-2515">
    <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
      <p class="u-small-text u-text u-text-variant u-text-1">System Generated By KHL</p>
    </div>
  </footer>
</body>
<script type="text/javascript">
  var auto_refresh = setInterval(
      function() {
          $.ajax({
              type: 'POST',
              url: 'showHPI.php',
              success: function(data) {
                  var dt = data.split("@");
                  var chart1 = new CanvasJS.Chart("chartContainer1", {
                      animationEnabled: true,
                      data: [{
                          type: "pie",
                          startAngle: 240,
                          yValueFormatString: "##0.00\"%\"",
                          indexLabel: "{label} {y}",
                          dataPoints: [{
                                  y: dt[3],
                                  label: "Alsumah Ega Kalita ("+dt[0]+" Suara)"
                              },
                              {
                                  y: dt[4],
                                  label: "Rofi'atul Ummah ("+dt[1]+" Suara)"
                              },
                              {
                                  y: dt[5],
                                  label: "Golput/Belum Memilih ("+dt[2]+" Suara)"
                              }
                          ]
                      }]
                  });
                  chart1.render();
              }
          })
      }, 30000);
</script>
</html>